baseURL = "http://htaidirt.com/"
languageCode = "en-us"
title = "Hassen Taidirt"
theme = "minimal"
disqusShortname = "htaidirt" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Hassen Taidirt"
    description = "Machine Learning engineer. Freelancer."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:htaidirt@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/htaidirt/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/htaidirt/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/htaidirt/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/1201298/htaidirt"
    name = "stack-overflow"
    weight = 5
